package prole;

import prole.puntos.MyPuntos;
import prole.semantico.MyETDSDesc;
import prole.afd.GrafoAFD;
import prole.afd.AFD;
import prole.afd.Opcion5;
import edu.uci.ics.jung.visualization.VisualizationViewer;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import prole.sintactico.SintaxException;

/**
 * Menú principal con las opciones de la app.
 *
 * @author diego
 */
public class Menu extends JFrame {

    public static String fileName;
    public static File file;
    public static AFD automata;
    public static String cadena;
    public static String[] tokens;

    /**
     * Constructor que inicializa los elementos del menú.
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonOpcion2 = new javax.swing.JButton();
        botonOpcion3 = new javax.swing.JButton();
        botonOpcion4 = new javax.swing.JButton();
        botonOpcion5 = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelArchivo = new javax.swing.JLabel();
        labelCadena = new javax.swing.JLabel();
        botonOpcion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonOpcion2.setText("2) Cargar un autómata");
        botonOpcion2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion2ActionPerformed(evt);
            }
        });

        botonOpcion3.setText("3) Introducir una cadena");
        botonOpcion3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion3ActionPerformed(evt);
            }
        });

        botonOpcion4.setText("4) Reconocer cadena");
        botonOpcion4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion4ActionPerformed(evt);
            }
        });

        botonOpcion5.setText("5) Reconocer cadena paso a paso");
        botonOpcion5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion5ActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        labelTitulo.setText("AFD y AFND");

        labelArchivo.setText("Autómata cargado:");

        labelCadena.setText("Cadena cargada:");

        botonOpcion1.setText("1) Test completo");
        botonOpcion1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTitulo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(botonOpcion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonOpcion3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonOpcion5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonOpcion4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonOpcion1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 40, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTitulo)
                .addGap(34, 34, 34)
                .addComponent(labelArchivo)
                .addGap(18, 18, 18)
                .addComponent(labelCadena)
                .addGap(27, 27, 27)
                .addComponent(botonOpcion1)
                .addGap(18, 18, 18)
                .addComponent(botonOpcion2)
                .addGap(18, 18, 18)
                .addComponent(botonOpcion3)
                .addGap(18, 18, 18)
                .addComponent(botonOpcion4)
                .addGap(18, 18, 18)
                .addComponent(botonOpcion5)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Mostrar todos las partes del proyecto.
     *
     * @param evt Acción sobre el botón.
     */
    private void botonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion1ActionPerformed


    }//GEN-LAST:event_botonOpcion1ActionPerformed

    /**
     * Introducir un autómata leyendo un archivo ".txt".
     *
     * @param evt Acción sobre el botón.
     */
    private void botonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion2ActionPerformed
        //abrir popup para elegir el archivo
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Elegir un archivo .txt");
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".txt", "txt");
        fc.setFileFilter(filter);
        int input = fc.showOpenDialog(this);
        //leer archivo
        if (input == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            fileName = file.getName();
            //crear el arbol
            MyETDSDesc parser = new MyETDSDesc();
            try {
                if (parser.parse(file)) {
                    System.out.println("Correcto");
                    //Inicia el algoritmo
                    labelArchivo.setText("Autómata cargado: " + fileName);
                    automata = MyPuntos.genAFD(parser.getAST());
                } else {
                    System.out.println("Incorrecto");
                }
            } catch (IOException ex) {

            } catch (SintaxException ex) {

            }
        }
    }//GEN-LAST:event_botonOpcion2ActionPerformed

    /**
     * Introducir una cadena para reconocer".
     *
     * @param evt Acción sobre el botón.
     */
    private void botonOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion3ActionPerformed
        try {
            Object input = JOptionPane.showInputDialog(this,
                    "Cadena:", "Introducir una cadena", JOptionPane.QUESTION_MESSAGE);
            if (input != null) {
                String s = String.valueOf(input);
                if (s.length() <= 20) { //longitud máxima 20
                    cadena = s;
                    tokens = s.split(" ");
                    labelCadena.setText("Cadena cargada: '" + cadena + "'");
                } else {
                    throw new Exception();
                }
            }
        } catch (Exception e) {
            //mensaje de error cuando la cadena no es válida
            JOptionPane.showMessageDialog(this, "Cadena no válida.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonOpcion3ActionPerformed

    /**
     * Reconocer la cadena mediante el autómata de una vez.
     *
     * @param evt Acción sobre el botón.
     */
    private void botonOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion4ActionPerformed
        try {
            if (automata == null) {
                throw new Exception("No hay ningún autómata cargado.");
            }
            if (cadena == null) {
                throw new Exception("No hay ninguna cadena cargada.");
            }
            //reconocer cadena
            boolean reconocida = automata.reconocer(tokens);
            String mensaje;
            if (reconocida) {
                mensaje = "Cadena '" + cadena + "' aceptada";
            } else {
                mensaje = "Cadena '" + cadena + "' rechazada";
            }
            //crear grafo
            VisualizationViewer<String, String> grafo = null;
            grafo = GrafoAFD.crear(Menu.automata);
            //crear el JFrame y mostrar el grafo
            JFrame frame = new JFrame(fileName);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.add(grafo);
            frame.setBounds(600, 50, 800, 800);
            frame.setVisible(true);
            //popup que informa sobre el reconocimiento de la cadena
            JOptionPane.showMessageDialog(this, mensaje, "Reconocer cadena", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            //mensaje de aviso cuando no hay autómata/cadena
            JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonOpcion4ActionPerformed

    /**
     * Reconocer la cadena mediante el autómata paso a paso.
     *
     * @param evt Acción sobre el botón.
     */
    private void botonOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion5ActionPerformed
        try {
            if (automata == null) {
                throw new Exception("No hay ningún autómata cargado.");
            }
            if (cadena == null) {
                throw new Exception("No hay ninguna cadena cargada.");
            }
            //abrir frame Opcion5
            Opcion5 f = new Opcion5(automata, cadena);
            f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            f.setBounds(100, 300, 500, 240);
            f.setTitle("Paso a paso");
            f.setVisible(true);
        } catch (Exception e) {
            //mensaje de aviso cuando no hay autómata/cadena
            JOptionPane.showMessageDialog(this, e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonOpcion5ActionPerformed

    /**
     * Método principal para mostrar el menú.
     *
     * @param args Argumentos.
     */
    public static void main(String args[]) {
        Menu m = new Menu();
        m.setDefaultCloseOperation(EXIT_ON_CLOSE);
        m.setBounds(200, 200, 370, 450);
        m.setTitle("PL - Proyecto");
        m.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOpcion1;
    private javax.swing.JButton botonOpcion2;
    private javax.swing.JButton botonOpcion3;
    private javax.swing.JButton botonOpcion4;
    private javax.swing.JButton botonOpcion5;
    private javax.swing.JLabel labelArchivo;
    private javax.swing.JLabel labelCadena;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
