package prole;

import prole.afd.*;
import javax.swing.*;
import edu.uci.ics.jung.visualization.VisualizationViewer;

/**
 * Muestra el reconocimiento de una cadena por el AFD paso a paso.
 *
 * @author Diego Francisco Darias Pino
 */
public class Visualizador extends JFrame {

    public int pos;
    public String cadena;
    public String[] tokens;
    public boolean acepta;
    public AFD afd;
    public VisualizationViewer<String, String> grafo;
    public JFrame gFrame;

    /**
     * Constructor.
     *
     * @param a AFD.
     * @param c String con la cadena de símbolos a comprobar.
     * @param g Ventana para mostrar el grafo.
     */
    public Visualizador(AFD a, String c, JFrame g) {
        //Inicializa los atributos
        pos = 0;
        cadena = c;
        tokens = c.split(" ");
        afd = a;
        gFrame = g;
        initComponents();

        //Actualiza la etiqueta cadena
        labelString.setText("Cadena: '" + c + "'");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonNext = new javax.swing.JButton();
        labelString = new javax.swing.JLabel();
        labelTran = new javax.swing.JLabel();
        labelChar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonNext.setText("Siguiente");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        labelString.setText("Cadena:");

        labelTran.setText("Última transición:");

        labelChar.setText("Último carácter:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonNext)
                    .addComponent(labelTran)
                    .addComponent(labelString)
                    .addComponent(labelChar))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelString)
                .addGap(18, 18, 18)
                .addComponent(labelTran)
                .addGap(18, 18, 18)
                .addComponent(labelChar)
                .addGap(34, 34, 34)
                .addComponent(buttonNext)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Avanza en el reconocimiento de la cadena cuando se pulsa el botón
     * "Siguiente".
     *
     * @param evt Acción sobre el botón.
     */
    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        //Crea el grafo
        JPanel panel = new JPanel();
        //Si no ha consumido todos los simbolos o llegado a uno no valido
        if (pos >= 0 && pos < tokens.length) {
            //Toma el siguiente caracter
            String carac = tokens[pos];
            //Comprueva si es consumido por el AFD
            acepta = afd.paso(carac);
            //Si es asi
            if (acepta) {
                //Avanza en la cadena de entrada
                pos++;
                //Actualiza las etiquetas de la ventana
                labelChar.setText("Último carácter: '" + carac + "'");
                labelTran.setText("Última transición: " + afd.ultimaT);
                //Muestra el cambio de estado
                grafo = GrafoAFD.crear(afd);
                panel.add(grafo);
                gFrame.add(grafo);
                gFrame.setVisible(true);
            } else {
                //Marca la cadena como rechazada
                pos = -1;
            }
        } else {
            //Si se ha consumido la cadena completa o se ha rechazado
            String mensaje;
            //Muestra un mensaje con el resultado
            if (acepta && pos == tokens.length && afd.verde.ultimo) {
                mensaje = "Cadena '" + cadena + "' aceptada";
            } else {
                mensaje = "Cadena '" + cadena + "' rechazada";
            }
            //Pop-up con el mensaje
            JOptionPane.showMessageDialog(this, mensaje, "Reconocer cadena", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonNextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNext;
    private javax.swing.JLabel labelChar;
    private javax.swing.JLabel labelString;
    private javax.swing.JLabel labelTran;
    // End of variables declaration//GEN-END:variables
}
